/**
 * Phase 2 — Recommendation Detail Component i18n Tests (Strict TDD)
 *
 * ⚠️ ORDER MATTERS: Spanish tests first, then English.
 */
import { describe, it, expect, vi, beforeAll } from 'vitest';
import { TestBed } from '@angular/core/testing';
import { LOCALE_ID, Component, signal } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient } from '@angular/common/http';
import { loadTranslations } from '@angular/localize';
import { RecommendationDetailComponent } from './recommendation-detail.component';
import { AgronomicRecommendationStore } from '../../../application/agronomic-recommendation.store';

@Component({ template: '' })
class DummyComponent {}

function createMockStore(overrides: Record<string, unknown> = {}) {
  const defaults = {
    isAgronomist: () => true,
    recommendationDetail: signal(null),
    recommendationDetailLoading: signal(false),
    recommendationDetailError: signal(''),
    recommendationActionLoading: signal(''),
    recommendationActionError: signal(''),
    recommendationActionSuccess: signal(''),
    linkedAlert: signal(null),
    ...overrides,
  };
  return {
    ...defaults,
    loadRecommendationDetail: vi.fn(),
    approveRecommendation: vi.fn(() => ({ subscribe: vi.fn() })),
    publishRecommendation: vi.fn(() => ({ subscribe: vi.fn() })),
  } as unknown as AgronomicRecommendationStore;
}

function setupTestBed(locale: 'es' | 'en', store: ReturnType<typeof createMockStore>) {
  return TestBed.configureTestingModule({
    imports: [RecommendationDetailComponent],
    providers: [
      { provide: LOCALE_ID, useValue: locale },
      { provide: AgronomicRecommendationStore, useValue: store },
      provideRouter([
        { path: 'recomendaciones', component: DummyComponent },
        { path: 'recomendaciones/:id', component: DummyComponent },
        { path: 'alertas', component: DummyComponent },
        { path: 'alertas/:id', component: DummyComponent },
      ]),
      provideHttpClient(),
    ],
  });
}

const EN: Record<string, string> = {
  'rec.detail.back': '← Back to recommendations',
  'rec.detail.loading': 'Loading detail...',
  'rec.detail.generatedByAI': 'Generated by AI',
  'rec.detail.generatedByAgronomist': 'Drafted by agronomist',
  'rec.detail.description': 'Description',
  'rec.detail.recommendedAction': 'Recommended Action',
  'rec.detail.relatedAlert': 'Related Alert',
  'rec.detail.sensorData': 'Sensor Data',
  'rec.detail.expectedRange': 'Expected Range',
  'rec.detail.summary': 'Summary',
  'rec.detail.publicationInfo': 'Publication Info',
  'rec.detail.plantation': 'Plantation',
  'rec.detail.zone': 'Zone',
  'rec.detail.reviewedBy': 'Reviewed by',
  'rec.detail.publishedOn': 'Published on',
  'rec.detail.pendingReview': 'Pending review',
  'rec.detail.notPublished': 'Not published',
  'rec.detail.approveBtn': 'Approve recommendation',
  'rec.detail.approving': 'Approving...',
  'rec.detail.publishBtn': 'Publish recommendation',
  'rec.detail.publishing': 'Publishing...',
  'rec.detail.priority.critical': 'Critical',
  'rec.detail.priority.high': 'High',
  'rec.detail.priority.medium': 'Medium',
  'rec.detail.priority.low': 'Low',
  'rec.detail.status.draft': 'Draft',
  'rec.detail.status.pendingReview': 'Pending review',
  'rec.detail.status.approved': 'Approved',
  'rec.detail.status.published': 'Published',
};

function mockRec(overrides: Record<string, unknown> = {}) {
  return {
    id: 1, title: 'Test Rec', description: 'A test description',
    plantationName: 'Finca Test', zoneName: 'Zona A',
    priority: 'high', status: 'pending_review',
    recommendedAction: 'Apply calcium',
    generatedBy: 'ai', alertId: null, alertTitle: '',
    reviewedByAgronomistName: null, publishedAt: null,
    ...overrides,
  };
}

// ═══════════════════════════════════════════════════════════════════════
//  SPANISH TESTS
// ═══════════════════════════════════════════════════════════════════════

describe('RecommendationDetailComponent — i18n (Spanish)', () => {
  it('should show Spanish back link and loading text', async () => {
    const store = createMockStore({ recommendationDetailLoading: () => true });
    await setupTestBed('es', store).compileComponents();
    const fixture = TestBed.createComponent(RecommendationDetailComponent);
    fixture.detectChanges();
    const el = fixture.nativeElement as HTMLElement;
    expect(el.textContent).toContain('Volver a recomendaciones');
    expect(el.textContent).toContain('Cargando detalle');
  });

  it('should show Spanish section headings', async () => {
    const store = createMockStore({ recommendationDetail: signal(mockRec()) });
    await setupTestBed('es', store).compileComponents();
    const fixture = TestBed.createComponent(RecommendationDetailComponent);
    fixture.detectChanges();
    const el = fixture.nativeElement as HTMLElement;
    expect(el.textContent).toContain('Descripcion');
    expect(el.textContent).toContain('Accion recomendada');
  });

  it('should show Spanish generated-by label', async () => {
    const store = createMockStore({ recommendationDetail: signal(mockRec({ generatedBy: 'ai' })) });
    await setupTestBed('es', store).compileComponents();
    const fixture = TestBed.createComponent(RecommendationDetailComponent);
    fixture.detectChanges();
    const el = fixture.nativeElement as HTMLElement;
    expect(el.textContent).toContain('Generada por IA');
  });

  it('should show Spanish summary sidebar', async () => {
    const store = createMockStore({ recommendationDetail: signal(mockRec()) });
    await setupTestBed('es', store).compileComponents();
    const fixture = TestBed.createComponent(RecommendationDetailComponent);
    fixture.detectChanges();
    const el = fixture.nativeElement as HTMLElement;
    expect(el.textContent).toContain('Resumen');
    expect(el.textContent).toContain('Informacion de publicacion');
    expect(el.textContent).toContain('Plantacion');
    expect(el.textContent).toContain('Zona');
    expect(el.textContent).toContain('Revisada por');
    expect(el.textContent).toContain('Publicada el');
  });

  it('should show Spanish approve/publish buttons', async () => {
    const store = createMockStore({ recommendationDetail: signal(mockRec({ status: 'pending_review' })) });
    await setupTestBed('es', store).compileComponents();
    const fixture = TestBed.createComponent(RecommendationDetailComponent);
    fixture.detectChanges();
    const el = fixture.nativeElement as HTMLElement;
    expect(el.textContent).toContain('Aprobar recomendacion');
  });

  it('should show Spanish priority/status labels', async () => {
    const store = createMockStore({ recommendationDetail: signal(mockRec({ priority: 'critical', status: 'approved' })) });
    await setupTestBed('es', store).compileComponents();
    const fixture = TestBed.createComponent(RecommendationDetailComponent);
    fixture.detectChanges();
    const el = fixture.nativeElement as HTMLElement;
    expect(el.textContent).toContain('Critica');
    expect(el.textContent).toContain('Aprobada');
  });

  it('should show Spanish sensor data section when linked alert', async () => {
    const store = createMockStore({
      recommendationDetail: signal(mockRec({ alertId: 1, alertTitle: 'Temp alert' })),
      linkedAlert: signal({ id: 1, label: 'Temperatura', alertLevel: 'critical', triggeredValue: 35, thresholdMin: 20, thresholdMax: 30, variableType: 'temperature', zoneName: 'Z1' }),
    });
    await setupTestBed('es', store).compileComponents();
    const fixture = TestBed.createComponent(RecommendationDetailComponent);
    fixture.detectChanges();
    const el = fixture.nativeElement as HTMLElement;
    expect(el.textContent).toContain('Datos del sensor');
    expect(el.textContent).toContain('Rango esperado');
  });
});

// ═══════════════════════════════════════════════════════════════════════
//  ENGLISH TESTS
// ═══════════════════════════════════════════════════════════════════════

describe('RecommendationDetailComponent — i18n (English)', () => {
  beforeAll(() => {
    loadTranslations(EN);
  });

  it('should show English back link and loading text', async () => {
    const store = createMockStore({ recommendationDetailLoading: () => true });
    await setupTestBed('en', store).compileComponents();
    const fixture = TestBed.createComponent(RecommendationDetailComponent);
    fixture.detectChanges();
    const el = fixture.nativeElement as HTMLElement;
    expect(el.textContent).toContain('Back to recommendations');
    expect(el.textContent).toContain('Loading detail');
  });

  it('should show English section headings', async () => {
    const store = createMockStore({ recommendationDetail: signal(mockRec()) });
    await setupTestBed('en', store).compileComponents();
    const fixture = TestBed.createComponent(RecommendationDetailComponent);
    fixture.detectChanges();
    const el = fixture.nativeElement as HTMLElement;
    expect(el.textContent).toContain('Description');
    expect(el.textContent).toContain('Recommended Action');
  });

  it('should show English generated-by label', async () => {
    const store = createMockStore({ recommendationDetail: signal(mockRec({ generatedBy: 'manual' })) });
    await setupTestBed('en', store).compileComponents();
    const fixture = TestBed.createComponent(RecommendationDetailComponent);
    fixture.detectChanges();
    const el = fixture.nativeElement as HTMLElement;
    expect(el.textContent).toContain('Drafted by agronomist');
  });

  it('should show English summary sidebar', async () => {
    const store = createMockStore({ recommendationDetail: signal(mockRec()) });
    await setupTestBed('en', store).compileComponents();
    const fixture = TestBed.createComponent(RecommendationDetailComponent);
    fixture.detectChanges();
    const el = fixture.nativeElement as HTMLElement;
    expect(el.textContent).toContain('Summary');
    expect(el.textContent).toContain('Publication Info');
    expect(el.textContent).toContain('Plantation');
    expect(el.textContent).toContain('Zone');
    expect(el.textContent).toContain('Reviewed by');
    expect(el.textContent).toContain('Published on');
  });

  it('should show English approve button', async () => {
    const store = createMockStore({ recommendationDetail: signal(mockRec({ status: 'pending_review' })) });
    await setupTestBed('en', store).compileComponents();
    const fixture = TestBed.createComponent(RecommendationDetailComponent);
    fixture.detectChanges();
    const el = fixture.nativeElement as HTMLElement;
    expect(el.textContent).toContain('Approve recommendation');
  });

  it('should show English priority/status labels', async () => {
    const store = createMockStore({ recommendationDetail: signal(mockRec({ priority: 'high', status: 'approved' })) });
    await setupTestBed('en', store).compileComponents();
    const fixture = TestBed.createComponent(RecommendationDetailComponent);
    fixture.detectChanges();
    const el = fixture.nativeElement as HTMLElement;
    expect(el.textContent).toContain('High');
    expect(el.textContent).toContain('Approved');
  });
});
