import { signal } from '@angular/core';
import { of } from 'rxjs';
import { vi } from 'vitest';
import { TranslationService } from '../../i18n/translation.service';
import { AgronomicRecommendationStore } from '../application/agronomic-recommendation.store';
import { Recommendation } from '../domain/model/recommendation.entity';

/** Flat keys used by recommendation views — mirrors assets/i18n. */
const ES: Record<string, string> = {
  'rec.list.backDashboard': 'Dashboard',
  'rec.list.badge.agronomist': 'Segmento agrónomo',
  'rec.list.badge.grower': 'Segmento productor',
  'rec.list.heading': 'Recomendaciones',
  'rec.list.subtitle.agronomist':
    'Gestiona recomendaciones por sector o generales: revisa, aprueba y publica.',
  'rec.list.subtitle.grower': 'Consulta las recomendaciones agronómicas publicadas por tu agrónomo.',
  'rec.list.counter': 'recomendaciones',
  'rec.list.tab.pending': 'Pendientes',
  'rec.list.tab.published': 'Publicadas',
  'rec.list.scope.sector': 'Por sector',
  'rec.list.scope.general': 'Generales',
  'rec.list.context.sector': 'Sector #{{id}}',
  'rec.list.context.general': 'Recomendaciones generales (toda la operación)',
  'rec.list.type.sector': 'Sectorial',
  'rec.list.type.general': 'General',
  'rec.list.newButton': '+ Nueva',
  'rec.list.refresh': 'Actualizar',
  'rec.list.loading': 'Cargando recomendaciones...',
  'rec.list.emptyPending': 'Sin pendientes',
  'rec.list.emptyPendingDesc': 'No hay recomendaciones que requieran revisión en este alcance.',
  'rec.list.emptyPublished': 'Sin publicadas',
  'rec.list.emptyPublishedDesc': 'Aún no se han publicado recomendaciones en este alcance.',
  'rec.list.createFirst': 'Crear primera recomendación',
  'rec.list.recommendedAction': 'Acción recomendada',
  'rec.list.createdAt': 'Fecha de creación',
  'rec.list.noIdHint': 'Sin id en el API — no se puede abrir el detalle.',
  'rec.list.priority.critical': 'Crítica',
  'rec.list.priority.high': 'Alta',
  'rec.list.priority.medium': 'Media',
  'rec.list.priority.low': 'Baja',
  'rec.list.status.pendingReview': 'Pendiente',
  'rec.list.status.approved': 'Aprobada',
  'rec.list.status.published': 'Publicada',
  'rec.form.back': 'Volver a recomendaciones',
  'rec.form.loading': 'Cargando formulario...',
  'rec.form.title': 'Nueva recomendación',
  'rec.form.subtitle': 'Redacta la recomendación. Se envía como content al backend (sector o general).',
  'rec.form.scope': 'Alcance',
  'rec.form.scopeSector': 'Sector específico',
  'rec.form.scopeGeneral': 'General (sin sector)',
  'rec.form.sector': 'ID de sector',
  'rec.form.sectorHelp': 'Sector configurado por administración (demo usa el sector del entorno).',
  'rec.form.titleInput': 'Título',
  'rec.form.titlePlaceholder': 'Ej. Aumentar riego en sector 1',
  'rec.form.description': 'Descripción',
  'rec.form.descriptionPlaceholder': 'Describe el contexto y la justificación de la recomendación...',
  'rec.form.recommendedAction': 'Acción recomendada',
  'rec.form.actionOptional': '(opcional)',
  'rec.form.actionPlaceholder': 'Ej. Ajustar caudal y revisar bomba',
  'rec.form.priority': 'Prioridad',
  'rec.form.priorityInText': '(en texto)',
  'rec.form.priorityLow': 'Baja',
  'rec.form.priorityMedium': 'Media',
  'rec.form.priorityHigh': 'Alta',
  'rec.form.priorityCritical': 'Crítica',
  'rec.form.save': 'Crear recomendación',
  'rec.form.saving': 'Guardando...',
  'rec.form.cancel': 'Cancelar',
  'rec.detail.back': 'Volver a recomendaciones',
  'rec.detail.loading': 'Cargando detalle...',
  'rec.detail.description': 'Descripción',
  'rec.detail.recommendedAction': 'Acción recomendada',
  'rec.detail.summary': 'Resumen',
  'rec.detail.publicationInfo': 'Información de publicación',
  'rec.detail.scope': 'Alcance',
  'rec.detail.id': 'Identificador',
  'rec.detail.zone': 'Zona',
  'rec.detail.type.sector': 'Sectorial',
  'rec.detail.type.general': 'General',
  'rec.detail.reviewedBy': 'Revisada por',
  'rec.detail.publishedOn': 'Publicada el',
  'rec.detail.pendingReview': 'Pendiente de revisión',
  'rec.detail.notPublished': 'No publicada',
  'rec.detail.approveBtn': 'Aprobar recomendación',
  'rec.detail.approving': 'Aprobando...',
  'rec.detail.publishBtn': 'Publicar recomendación',
  'rec.detail.publishing': 'Publicando...',
  'rec.detail.created': 'Creada',
  'rec.detail.agronomistFallback': 'Agrónomo',
  'rec.detail.priority.critical': 'Crítica',
  'rec.detail.priority.high': 'Alta',
  'rec.detail.priority.medium': 'Media',
  'rec.detail.priority.low': 'Baja',
  'rec.detail.status.pendingReview': 'Pendiente de revisión',
  'rec.detail.status.approved': 'Aprobada',
  'rec.detail.status.published': 'Publicada',
  'rec.detail.error.invalid': 'Recomendación no válida.',
};

const EN: Record<string, string> = {
  'rec.list.backDashboard': 'Dashboard',
  'rec.list.badge.agronomist': 'Agronomist segment',
  'rec.list.badge.grower': 'Grower segment',
  'rec.list.heading': 'Recommendations',
  'rec.list.subtitle.agronomist':
    'Manage sector or general recommendations: review, approve and publish.',
  'rec.list.subtitle.grower': 'View agronomic recommendations published by your agronomist.',
  'rec.list.counter': 'recommendations',
  'rec.list.tab.pending': 'Pending',
  'rec.list.tab.published': 'Published',
  'rec.list.scope.sector': 'By sector',
  'rec.list.scope.general': 'General',
  'rec.list.context.sector': 'Sector #{{id}}',
  'rec.list.context.general': 'General recommendations (whole operation)',
  'rec.list.type.sector': 'Sector-specific',
  'rec.list.type.general': 'General',
  'rec.list.newButton': '+ New',
  'rec.list.refresh': 'Refresh',
  'rec.list.loading': 'Loading recommendations...',
  'rec.list.emptyPending': 'No pending',
  'rec.list.emptyPendingDesc': 'No recommendations require review in this scope.',
  'rec.list.emptyPublished': 'No published',
  'rec.list.emptyPublishedDesc': 'No recommendations have been published in this scope yet.',
  'rec.list.createFirst': 'Create first recommendation',
  'rec.list.recommendedAction': 'Recommended action',
  'rec.list.createdAt': 'Created on',
  'rec.list.noIdHint': 'No id from the API — detail cannot be opened.',
  'rec.list.priority.critical': 'Critical',
  'rec.list.priority.high': 'High',
  'rec.list.priority.medium': 'Medium',
  'rec.list.priority.low': 'Low',
  'rec.list.status.pendingReview': 'Pending review',
  'rec.list.status.approved': 'Approved',
  'rec.list.status.published': 'Published',
  'rec.form.back': 'Back to recommendations',
  'rec.form.loading': 'Loading form...',
  'rec.form.title': 'New recommendation',
  'rec.form.subtitle': 'Write the recommendation. It is sent as content to the backend (sector or general).',
  'rec.form.scope': 'Scope',
  'rec.form.scopeSector': 'Sector-specific',
  'rec.form.scopeGeneral': 'General (no sector)',
  'rec.form.sector': 'Sector ID',
  'rec.form.sectorHelp': 'Sector configured by administration (demo uses the environment sector).',
  'rec.form.titleInput': 'Title',
  'rec.form.titlePlaceholder': 'E.g. Increase irrigation in sector 1',
  'rec.form.description': 'Description',
  'rec.form.descriptionPlaceholder': 'Describe the context and rationale for the recommendation...',
  'rec.form.recommendedAction': 'Recommended action',
  'rec.form.actionOptional': '(optional)',
  'rec.form.actionPlaceholder': 'E.g. Adjust flow and check pump',
  'rec.form.priority': 'Priority',
  'rec.form.priorityInText': '(in text)',
  'rec.form.priorityLow': 'Low',
  'rec.form.priorityMedium': 'Medium',
  'rec.form.priorityHigh': 'High',
  'rec.form.priorityCritical': 'Critical',
  'rec.form.save': 'Create recommendation',
  'rec.form.saving': 'Saving...',
  'rec.form.cancel': 'Cancel',
  'rec.detail.back': 'Back to recommendations',
  'rec.detail.loading': 'Loading detail...',
  'rec.detail.description': 'Description',
  'rec.detail.recommendedAction': 'Recommended action',
  'rec.detail.summary': 'Summary',
  'rec.detail.publicationInfo': 'Publication info',
  'rec.detail.scope': 'Scope',
  'rec.detail.id': 'Identifier',
  'rec.detail.zone': 'Zone',
  'rec.detail.type.sector': 'Sector-specific',
  'rec.detail.type.general': 'General',
  'rec.detail.reviewedBy': 'Reviewed by',
  'rec.detail.publishedOn': 'Published on',
  'rec.detail.pendingReview': 'Pending review',
  'rec.detail.notPublished': 'Not published',
  'rec.detail.approveBtn': 'Approve recommendation',
  'rec.detail.approving': 'Approving...',
  'rec.detail.publishBtn': 'Publish recommendation',
  'rec.detail.publishing': 'Publishing...',
  'rec.detail.created': 'Created',
  'rec.detail.agronomistFallback': 'Agronomist',
  'rec.detail.priority.critical': 'Critical',
  'rec.detail.priority.high': 'High',
  'rec.detail.priority.medium': 'Medium',
  'rec.detail.priority.low': 'Low',
  'rec.detail.status.pendingReview': 'Pending review',
  'rec.detail.status.approved': 'Approved',
  'rec.detail.status.published': 'Published',
  'rec.detail.error.invalid': 'Invalid recommendation.',
};

/** Mock TranslationService for recommendation component tests. */
export function createTranslationMock(locale: 'es' | 'en'): Pick<TranslationService, 'translate'> {
  const map = locale === 'en' ? EN : ES;
  return {
    translate: (key: string) => map[key] ?? key,
  };
}

export function mockRecommendation(overrides: Partial<Recommendation> = {}): Recommendation {
  return {
    id: 1,
    sectorId: 1,
    content: 'Aumentar riego\n\nDetalle de prueba.\n\nAcción recomendada: Ajustar caudal\nPrioridad: high',
    type: 'SectorSpecific',
    status: 'pending_review',
    createdAt: '2026-01-01T00:00:00Z',
    approvedAt: null,
    publishedAt: null,
    clientKey: 'id:1',
    title: 'Aumentar riego',
    description: 'Detalle de prueba.',
    recommendedAction: 'Ajustar caudal',
    priority: 'high',
    hasExplicitPriority: true,
    hasExplicitAction: true,
    scopeLabel: 'Sector #1',
    plantationName: 'Sector #1',
    zoneName: '',
    hasZone: false,
    generatedBy: 'manual',
    reviewedByAgronomistName: null,
    userId: 3,
    monitoringZoneId: 0,
    alertId: null,
    alertTitle: null,
    reviewedByAgronomistId: null,
    updatedAt: '2026-01-01T00:00:00Z',
    ...overrides,
  };
}

export function createRecStoreMock(overrides: Record<string, unknown> = {}): AgronomicRecommendationStore {
  const defaults = {
    isAgronomist: () => true,
    recommendations: signal<Recommendation[]>([]),
    recommendationsLoading: signal(false),
    recommendationsError: signal(''),
    listScope: signal<'sector' | 'general'>('sector'),
    listSectorId: signal(1),
    recommendationDetail: signal<Recommendation | null>(null),
    recommendationDetailLoading: signal(false),
    recommendationDetailError: signal(''),
    recommendationActionLoading: signal(''),
    recommendationActionError: signal(''),
    recommendationActionSuccess: signal(''),
    recommendationFormLoading: signal(false),
    recommendationFormSaving: signal(false),
    recommendationFormError: signal(''),
    formSectorId: signal(1),
    loadRecommendations: vi.fn(),
    setListScope: vi.fn(),
    loadRecommendationDetail: vi.fn(),
    approveRecommendation: vi.fn(() => of(mockRecommendation({ status: 'approved' }))),
    publishRecommendation: vi.fn(() => of(mockRecommendation({ status: 'published' }))),
    prepareForm: vi.fn(),
    createRecommendation: vi.fn(() => of(mockRecommendation())),
  };

  return { ...defaults, ...overrides } as unknown as AgronomicRecommendationStore;
}
